# ENV FILE FOR THE GITHUB ACTION RUNNING POSTGRESQL
APP_NAME=TousLesPrenoms
APP_ENV=testing
APP_KEY=base64:NTrXToqFZJlv48dgPc+kNpc3SBt333TfDnF1mDShsBg=
APP_DEBUG=true
APP_URL=http://localhost

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=touslesprenoms
DB_USERNAME=touslesprenoms
DB_PASSWORD=secret

DEBUGBAR_ENABLED=false
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
MAIL_MAILER=array

SCOUT_DRIVER=collection
